services:
  app:
    image: ransoftware/bookly-ai-backend-dev:latest
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - HOST=0.0.0.0
    volumes:
      - uploads_data:/app/uploads
    restart: unless-stopped

volumes:
  uploads_data:
